import "./globals.css";
import localFont from "next/font/local";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
//
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const ablation = localFont({src: './fonts/AblationBold.otf', variable: '--font-ablation'})
const ablation2 = localFont({src: './fonts/AblationBlack.otf', variable: '--font-ablation2'})
const sfPro = localFont({src: './fonts/SF-Pro-Display-Light.otf', variable: '--font-sfPro'})
const inter = localFont({src: './fonts/Inter.ttf', variable: '--font-inter'})

export default function RootLayout({children}) {
    return (
        <html lang="en" className={`${inter.variable} ${ablation.variable} ${ablation2.variable} ${sfPro.variable}`}>
        {children}
        </html>
    );
}
